window.REGIONS = {
  aichi: {
    regionId: "aichi",
    title: "愛知県のアジアンエステ",
    h1Label: "愛知県のアジアンエステ",
    rootLabel: "愛知県",
    mapCenter: { lat: 35.083, lng: 137.156 },
    mapZoom: 12,
    profileMapZoom: 11,
    geocodeSuffix: "愛知県",
    geocodeScopePattern: "愛知県|豊田市|岡崎市|安城市|刈谷市|西尾市",
    areaLabels: {
      nagoya: "名古屋・名駅・納屋橋",
      sakae: "栄",
      shinsakae: "新栄町・千種・今池",
      kanayama: "金山・熱田",
      kurokawa: "黒川・大曽根",
      hoshigaoka: "星ヶ丘・藤が丘",
      moriyama: "守山・小幡",
      otai: "小田井・比良",
      tokaidori: "東海通・高畑",
      kasadera: "笠寺・柴田",
      horita: "堀田・新瑞橋",
      tsurumai: "大須・鶴舞",
      showa: "名古屋・昭和区・天白区",
      komaki: "小牧・春日井",
      owari: "尾張・一宮",
      chita: "知多・大府・半田",
      toyota: "西三河・豊田・岡崎",
      toyohashi: "東三河・豊橋・豊川",
    },
    areaOrder: [
      "nagoya",
      "sakae",
      "shinsakae",
      "kanayama",
      "tsurumai",
      "kurokawa",
      "hoshigaoka",
      "showa",
      "moriyama",
      "otai",
      "tokaidori",
      "horita",
      "kasadera",
      "komaki",
      "owari",
      "chita",
      "toyota",
      "toyohashi",
    ],
    stationGroupRegions: [
      "nagoya",
      "sakae",
      "shinsakae",
      "kanayama",
      "kurokawa",
      "hoshigaoka",
      "moriyama",
      "otai",
      "tokaidori",
      "kasadera",
      "horita",
      "tsurumai",
      "showa",
    ],
    municipalityMap: {
      nagoya: ["名古屋市"],
      sakae: ["名古屋市"],
      shinsakae: ["名古屋市"],
      kanayama: ["名古屋市"],
      kurokawa: ["名古屋市"],
      hoshigaoka: ["名古屋市"],
      moriyama: ["名古屋市"],
      otai: ["名古屋市"],
      tokaidori: ["名古屋市"],
      kasadera: ["名古屋市"],
      horita: ["名古屋市"],
      tsurumai: ["名古屋市"],
      showa: ["名古屋市"],
      komaki: ["小牧市", "春日井市", "瀬戸市", "豊明市", "日進市", "犬山市", "長久手市"],
      owari: ["一宮市", "稲沢市", "江南市", "北名古屋市", "清須市", "岩倉市", "愛西市", "尾張旭市", "弥富市", "津島市", "あま市", "蟹江町", "大治町", "扶桑町"],
      chita: ["知多市", "大府市", "半田市", "東海市", "常滑市", "武豊町", "阿久比町", "東浦町"],
      toyota: ["豊田市", "岡崎市", "刈谷市", "知立市", "安城市", "高浜市", "碧南市", "みよし市", "西尾市", "幸田町"],
      toyohashi: ["豊橋市", "豊川市", "新城市", "蒲郡市", "田原市"],
    },
    roomLocationOverrides: {
      "https://www.esthe-ranking.jp/owari/shop-detail/f41d3134-7f58-450e-9c7e-ffe955f72138/": [
        {
          label: "木曽川駅",
          address: "愛知県一宮市木曽川町黒田山1-2",
          latitude: "",
          longitude: "",
          note: "フィットイージー 木曽川店付近着きましたらお電話してください。",
        },
        {
          label: "奥町駅",
          address: "35.31058761168509, 136.75743862450264",
          latitude: "35.31058761168509",
          longitude: "136.75743862450264",
          note: "マクドナルド一宮尾西店付近着きましたら電話してください。",
        },
      ],
      "https://www.esthe-ranking.jp/toyota/shop-detail/36151484-fd68-4f6f-941f-360ff124a937/": [
        {
          label: "安城駅",
          address: "35.027788136971594, 137.09918316798218",
          latitude: "35.027788136971594",
          longitude: "137.09918316798218",
          note: "ドミスーパー着きましたら電話してください。",
        },
      ],
    },
  },
};

window.CURRENT_REGION_ID = window.CURRENT_REGION_ID || "aichi";
